site_name: Sandbuy documentation
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'light blue'
  logo:
    icon: 'attach_money'
extra_css: 
  - 'extra.css'
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.superfences
  - attr_list
nav:
  - Introduction: index.md
  - Client configurtion: client_settings.md
  - Server configuration: server_settings.md
  - Price management: prices.md
  - Differences from Sandbox: patches.md
  - Advanced price system usage: advancedprices.md
  - Lua API:
    - Overview: lua/overview.md
    - Reference:
      - Gamemode hooks: lua/hooks.md
      - Price system: lua/pricer.md
      - Patching system: lua/patcher.md
